# Generated by Django 3.0 on 2019-12-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessing',
            fields=[
                ('source_id', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name=' id of video in the source')),
                ('status', models.CharField(choices=[('DW', 'Download'), ('WT', 'Waiting to upload'), ('IN_PR', 'In progress of uploading'), ('ERROR_MESS', 'Error message'), ('SUCC_UP', 'Successfully Uploaded')], default='DW', max_length=10)),
                ('error_message_video', models.TextField(blank=True, max_length=500)),
                ('youtube_id', models.CharField(max_length=250, unique=True, verbose_name='id of youtube uploaded video')),
                ('youtube_link', models.URLField(max_length=250, unique=True, verbose_name='link of the video from youtube')),
            ],
        ),
        migrations.AlterField(
            model_name='processing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processing',
            name='source_type',
            field=models.CharField(choices=[('GD', 'Gdrive type'), ('GPH', 'Gphotos type')], max_length=250, unique=True, verbose_name='source of the file'),
        ),
        migrations.DeleteModel(
            name='VideoProc',
        ),
        migrations.AddField(
            model_name='videoprocessing',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdrive.Processing'),
        ),
    ]
