# Generated by Django 3.0 on 2019-12-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdrive', '0002_auto_20191226_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processing',
            name='source_type',
            field=models.CharField(choices=[('GD', 'Gdrive type'), ('GPH', 'Gphotos type')], max_length=250, verbose_name='source of the file'),
        ),
        migrations.AlterField(
            model_name='videoprocessing',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vdrive.Processing'),
        ),
    ]
