# Generated by Django 3.0 on 2019-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0003_auto_20191230_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprocessing',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='id of youtube uploaded video'),
        ),
        migrations.AlterField(
            model_name='videoprocessing',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='link of the video from youtube'),
        ),
    ]
