# Generated by Django 3.0 on 2019-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0004_auto_20191230_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprocessing',
            name='status',
            field=models.CharField(choices=[('DW', 'Download'), ('WT', 'Waiting to upload'), ('IN_PR', 'In progress of uploading'), ('ERROR_MESS', 'Error message'), ('SUCC_UP', 'Successfully Uploaded')], default='WT', max_length=10),
        ),
    ]
