# Generated by Django 3.0 on 2020-01-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0005_auto_20191230_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProcessing',
        ),
    ]
