# Generated by Django 3.0 on 2020-01-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0006_delete_videoprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=250, verbose_name=' id of video in the source')),
                ('status', models.CharField(choices=[('WT', 'Waiting to upload'), ('DW', 'Download'), ('UPL', 'In progress of uploading'), ('ERROR_MESS', 'Error message'), ('SUCC_UP', 'Successfully Uploaded')], default='WT', max_length=10)),
                ('error_message_video', models.TextField(blank=True, max_length=500)),
                ('youtube_id', models.CharField(blank=True, max_length=250, verbose_name='id of youtube uploaded video')),
                ('youtube_link', models.URLField(blank=True, verbose_name='link of the video from youtube')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vdrive.Processing')),
            ],
        ),
    ]
