# Generated by Django 3.0 on 2020-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0007_videoprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessing',
            name='name',
            field=models.CharField(default=2, max_length=250, verbose_name='name of the video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoprocessing',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded')], default='waiting', max_length=10),
        ),
    ]
