# Generated by Django 3.0 on 2020-01-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdrive', '0008_auto_20200114_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=250, verbose_name=' id of video in the source')),
                ('name', models.CharField(max_length=250, verbose_name='name of the video')),
                ('source_type', models.CharField(choices=[('Google Drive', 'Gdrive type'), ('Google Photos', 'Gphotos type')], max_length=250, verbose_name='source of the file')),
                ('youtube_id', models.CharField(blank=True, max_length=250, verbose_name='id of youtube uploaded video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='processing',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='user',
        ),
        migrations.DeleteModel(
            name='VideoProcessing',
        ),
    ]
