# Generated by Django 3.0 on 2020-01-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0009_auto_20200115_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded')], default='waiting', max_length=50)),
                ('error_message_video', models.TextField(blank=True)),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vdrive.Video')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='vdrive.Video')),
            ],
        ),
    ]
