# Generated by Django 3.0 on 2020-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0011_auto_20200116_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprocessing',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded'), ('deleted', 'Successfully deleted')], default='waiting', max_length=50),
        ),
    ]
