# Generated by Django 3.0 on 2020-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0012_auto_20200122_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('waiting on drive', 'Waiting to upload'), ('deleted', 'Successfully deleted')], default='waiting on drive', max_length=50),
        ),
        migrations.AlterField(
            model_name='videoprocessing',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to upload'), ('download', 'Download'), ('uploading', 'In progress of uploading'), ('errors', 'Error message'), ('success', 'Successfully Uploaded')], default='waiting', max_length=50),
        ),
    ]
