# Generated by Django 3.0 on 2020-01-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0013_auto_20200122_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default=123, max_length=250, verbose_name='thumbnail of the video'),
            preserve_default=False,
        ),
    ]
