# Generated by Django 3.0 on 2020-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0015_auto_20200123_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.CharField(default=1, max_length=50, verbose_name='File size'),
            preserve_default=False,
        ),
    ]
