# Generated by Django 3.0 on 2020-01-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0016_video_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processing',
            options={'ordering': ['-date']},
        ),
    ]
