# Generated by Django 3.0 on 2020-01-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdrive', '0019_auto_20200127_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.CharField(max_length=250, verbose_name='File size'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(max_length=1000, verbose_name='thumbnail of the video'),
        ),
    ]
