# Generated by Django 3.0 on 2020-01-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdrive', '0020_auto_20200128_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to scan'), ('in_progress', 'Scanning'), ('success', 'Success'), ('error', 'Error')], default='waiting', max_length=50)),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
